### PR TITLE
#29 - Added non-prefixed version of flex-flow for non-Chrome browsers

### PR DESCRIPTION
**Pull request by awestmoreland**
I was unable to test locally as react isn't working for me, but I see the markup fine on production. Could do with someone verifying change, or push and be damned ;)

### CODE REVIEW

**Comment by jacebrowning** [comment]
I'll test it...

**Comment by jacebrowning** [comment]
Right now I'm seeing `GET https://api.github.com/orgs/friendlycode/repos 403 (Forbidden)` in my console.

**Comment by awestmoreland** [comment]
Hmm, I only changed one line of CSS, so I'm pretty sure that wouldn't affect it, but maybe @Crevax could weigh in too.

I don't see that error, but I also don't see the projects locally. I do see the projects on production, but @jacebrowning was having intermittent issues seeing them there yesterday. Sounds like an issue at Github?

**Comment by jacebrowning** [comment]
https://api.github.com/orgs/friendlycode/repos says it's being rate limited.

**Comment by awestmoreland** [comment]
Ah, good catch! Maybe we need to look into caching the projects daily (or even weekly) as part of #12.

**Comment by Crevax** [comment]
I'm surprised we're exceeding the 60/hr limit. While authenticating would increase our limit to 5000/hr, caching the results would be a good to do as well.

**Comment by awestmoreland** [comment]
Want me to add a bug/feature request, or is this still part of #12? Either way, we should probably document somewhere other than here :)

**Comment by jacebrowning** [comment]
Submit another issue.

:+1: This looks good to merge!

**Comment by awestmoreland** [comment]
:+1:

**Pull request merged**
